sudo: required
services: 
  - docker

before_install:
  - docker build -t danieldsouza93/docker-react -f Dockerfile.dev .

script:
  - docker run danieldsouza93/docker-react npm run test -- --coverage